services:
  - type: web
    name: my-fullstack-app
    env: node
    plan: free
    rootDir: ./backend
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
